version: 0.2

env:
  variables:
    LAMBDA_NAME: "index-photos"  

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t package
  build:
    commands:
      - echo "Packaging lambda..."
      - cp lambda_function.py package/
      - cd package
      - zip -r ../lambda.zip .
      - cd ..
  post_build:
    commands:
      - echo "Deploying to Lambda..."
      - aws lambda update-function-code --function-name $LAMBDA_NAME --zip-file fileb://lambda.zip

artifacts:
  files:
    - lambda.zip
